baseURL = 'http://blacksecc.github.io/' 
languageCode = 'en-us'
title = 'BlackSec is Cybersecurity Blog'
theme = 'PaperMod'

[params]
[params.profileMode]
enabled = true
title = "<Title>" # optional default will be site title
subtitle = "This is subtitle"
imageUrl = "<image link>" # optional
imageTitle = "<title of image as alt>" # optional
imageWidth = 120 # custom size
imageHeight = 120 # custom size
[params.profileMode.buttons]
name = Archive
url = "/archive"
name = Github
url = "https://github.com/"
[params.profileMode.buttons.socialIcons]
name = "<platform>"
url = "<link>"
name = "<platform 2>"
url = "<link2>"
