baseURL: 'http://blacksecc.github.io/' 
title: BlackSec is Cybersecurity Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: categories
                  url: categories/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Search
                  url: search/
                  weight: 10

    ru:
        languageName: "Russian"
        weight: 2
        title: BlackSec Блог по Кибербезопасности
        taxonomies:
          category: RUcategories
          tag: RUtags
          series: RUseries
        homeInfoParams:
            Title: Мое имя BlackSec
            Content: Я Офицер Кибербезопасности

            socialIcons:
              - name: twitter
                url: "https://twitter.com/"
              - name: github
                url: "https://github.com/"

        menu:
            main:
                - name: Archive
                  url: archives/
                  weight: 5
                - name: RUCategories
                  url: rucategories
                  weight: 10  
                - name: RUTags
                  url: rutags
                  weight: 10
                - name: Search
                  url: search/
                  weight: 10
                

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: BlackSec is Cybersecurity Blog
  description: "BlackSec is Cybersecurity Blog"
  keywords: [Blog, Cybersecurity, BlackSec, InfoSec, CeberSec]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["https://i.ibb.co/3pvSLTr/Component-4-1.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "BlackSec"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: My name is BlackSec.
    Content: I'm Cybersecurity Officer.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text 
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# menu:
#   main:
#     - identifier: categories
#       name: categories
#       url: /categories/
#       weight: 10
#     - identifier: tags
#       name: tags
#       url: /tags/
#       weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
