baseURL = 'http://blacksecc.github.io/' 
languageCode = 'en-us'
title = 'BlackSec is Cybersecurity Blog'
theme = 'PaperMod'

[params]
[params.profileMode]
enabled = true
title = "<Title>" # optional default will be site title
subtitle = "This is subtitle"
imageUrl = "<image link>" # optional
imageTitle = "<title of image as alt>" # optional
imageWidth = 120 # custom size
imageHeight = 120 # custom size

