baseURL: 'http://b7acksec.github.io/' 
title: BlackSec is Cybersecurity Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          archives: archives
          category: categories
          tag: tags
          search: search
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 11
                - name: Сategories
                  url: categories/
                  weight: 12
                - name: Tags
                  url: tags/
                  weight: 13
                - name: Search
                  url: search/
                  weight: 14

    ru:
        languageName: "Russian"
        weight: 2
        title: BlackSec Блог по Кибербезопасности
        taxonomies:
          ruarchives: Архив
          rucategory: Категории
          rutag: Теги
          rusearch: Поиск
        homeInfoParams:
            Title: Офицер по Кибербезопаснотси BlackSec
            Content: >
                - BlackSec офицер информационной безопасности из Средней Азии. Он знаком с ситуацией с кибербезопасностью в Центрально Азиатском регионе. BlackSec проводит исследования в области разведки киберугроз, тестирования на проникновение, компьютерной криминалистики и разрабатывает программное обеспечение для кибербезопасности.

            socialIcons:
              - name: twitter
                url: "https://twitter.com/"
              - name: github
                url: "https://github.com/"

        menu:
            main:
                - name: Архив
                  url: ruarchives/
                  weight: 11
                - name: Категории
                  url: rucategories/
                  weight: 12  
                - name: Теги
                  url: rutags/
                  weight: 13
                - name: Поиск
                  url: rusearch/
                  weight: 14
                

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: BlackSec is Cybersecurity Blog
  description: "BlackSec is Cybersecurity Blog"
  keywords: [Blog, Cybersecurity, BlackSec, InfoSec, CeberSec]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["https://i.ibb.co/3pvSLTr/Component-4-1.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"

  label:
    text: "BlackSec"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: Сybersecurity officer BlackSec
    Content: >
        - BlackSec information security officer from Central Asia. He is familiar with the Cybersecurity situation in the region. BlackSec conducts research in the fields of threat intelligence, penetration testing, forensics and develops cybersecurity software.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
